// for now this is a mock page and will be replaced with the actual order history page 
// this is ai generated code for now only
"use client";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { useEffect, useState } from "react";
import Link from "next/link";

export default function OrderHistory() {
    const [orders, setOrders] = useState([]);
    const [loading, setLoading] = useState(true);

    //mock orders generated by ai
    useEffect(() => {
        const mockOrders = [
            {
                id: 1,
                date: "2024-01-01",
                total: 100,
                status: "Delivered"
            },
            {
                id: 2,
                date: "2024-01-02",
                total: 200,
                status: "Shipped"
            },
            {
                id: 3,
                date: "2024-01-03",
                total: 300,
                status: "Processing"
            }
        ];
        setOrders(mockOrders);
        setLoading(false);
    }, []);

    const getStatusColor = (status) => {
        switch (status) {
            case "Delivered":
                return "text-green-600 bg-green-100 dark:text-green-400 dark:bg-green-900/20";
            case "Shipped":
                return "text-blue-600 bg-blue-100 dark:text-blue-400 dark:bg-blue-900/20";
            case "Processing":
                return "text-yellow-600 bg-yellow-100 dark:text-yellow-400 dark:bg-yellow-900/20";
            default:
                return "text-gray-600 bg-gray-100 dark:text-gray-400 dark:bg-gray-900/20";
        }
    };



    return (
        <div className="bg-background min-h-screen w-screen">
            <Header />
            
            <main className="p-4">
                <div className="max-w-4xl mx-auto">
                    <div className="bg-card-bg rounded-lg shadow-sm border border-card-border p-6">
                        <div className="flex items-center justify-between mb-6">
                            <h1 className="text-2xl font-bold text-text-primary">Order History</h1>
                            <Link 
                                href="/settings" 
                                className="text-text-primary hover:text-text-secondary transition-colors"
                            >
                                ← Back to Settings
                            </Link>
                        </div>

                        {loading ? (
                            <div className="flex justify-center items-center h-32">
                                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-text-primary"></div>
                            </div>
                        ) : orders.length === 0 ? (
                            <div className="text-center py-12">
                                <div className="text-6xl mb-4">📦</div>
                                <h2 className="text-xl font-semibold text-text-primary mb-2">No orders yet</h2>
                                <p className="text-text-secondary mb-6">Start shopping to see your order history here</p>
                                <Link 
                                    href="/products"
                                    className="inline-block bg-text-primary text-background px-6 py-3 rounded-lg hover:opacity-90 transition-opacity font-medium"
                                >
                                    Browse Products
                                </Link>
                            </div>
                        ) : (
                            <div className="space-y-4">
                                {orders.map((order) => (
                                    <div key={order.id} className="bg-background border border-card-border rounded-lg p-4 hover:shadow-md transition-shadow">
                                        <div className="flex justify-between items-start">
                                            <div>
                                                <h3 className="text-lg font-semibold text-text-primary">Order #{order.id}</h3>
                                                <p className="text-text-secondary">Placed on {order.date}</p>
                                            </div>
                                            <div className="text-right">
                                                <span className={`px-3 py-1 rounded-full text-sm font-medium ${getStatusColor(order.status)}`}>
                                                    {order.status}
                                                </span>
                                                <p className="text-xl font-bold text-text-primary mt-2">${order.total}</p>
                                            </div>
                                        </div>
                                    </div>
                                ))}
                            </div>
                        )}
                    </div>
                </div>
            </main>
            
            <Footer />
        </div>
    );
}